// src/pages/Marketing.vue
<template>
  <main class="marketing-page" aria-labelledby="marketing-hero-title">
    <!-- Hero -->
    <section class="marketing-hero">
      <div class="marketing-hero-inner">
        <div class="marketing-hero-copy">
          <h1 id="marketing-hero-title" class="marketing-hero-title">Marketing</h1>
          <p class="marketing-hero-subtitle">
            Unlock the Power of Secure Marketing with SolidProof. Our comprehensive range of meticulously vetted marketing solutions, in collaboration with top-tier agencies, empowers businesses to achieve their goals.
          </p>
          <div class="marketing-hero-ctas">
            <a href="https://t.me/solidproof_io" target="_blank" class="marketing-cta marketing-cta--primary">Request Marketing</a>
            <a href="#marketing-services" class="marketing-cta marketing-cta--ghost">Learn more</a>
          </div>
        </div>
        <div class="marketing-hero-art" aria-hidden="true">
          <div class="marketing-orb marketing-orb--lg"></div>
          <div class="marketing-orb marketing-orb--sm"></div>
          <svg class="marketing-hero-svg" viewBox="0 0 160 160" fill="none" aria-hidden="true">
            <defs>
              <linearGradient id="gm1" x1="0" y1="0" x2="1" y2="1">
                <stop offset="0" stop-color="#6AFFB3"/>
                <stop offset="1" stop-color="#8E60EE"/>
              </linearGradient>
            </defs>
            <circle cx="80" cy="80" r="72" stroke="url(#gm1)" stroke-width="2" opacity="0.6"/>
            <circle cx="80" cy="80" r="52" stroke="url(#gm1)" stroke-width="2" opacity="0.35"/>
            <circle cx="80" cy="80" r="28" stroke="url(#gm1)" stroke-width="2" opacity="0.25"/>
          </svg>
        </div>
      </div>
    </section>

    <!-- Intro -->
    <section class="marketing-intro">
      <div class="mi-wrap">
        <p class="mi-text">
          SolidProof offers clients a wide range of marketing solutions that have successfully passed our security checks. We are partnered with multiple high-class marketing agencies and work together with our clients to find the best solutions that suit their goals. Our marketing arsenal leaves no stone unturned, giving clients a one-stop place for all of their marketing needs. Going with SolidProof allows you to find the highest quality solutions at the best prices possible. We can assist with the following:
        </p>
      </div>
    </section>

    <!-- Services -->
    <section id="marketing-services" class="marketing-services" aria-labelledby="marketing-services-title">
      <div class="ms-wrap">
        <h2 id="marketing-services-title" class="ms-title">Marketing Services</h2>
        <div class="ms-grid">
          <div class="ms-item">
            <div class="ms-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none"><path d="M3 3v18h18" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M7 16v-5M12 16v-8M17 16v-3" stroke="#8E60EE" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </div>
            <h3 class="ms-item-title">Influencer Marketing</h3>
            <p class="ms-item-desc">Harness the power of influential individuals to promote your brand and drive engagement</p>
          </div>
          <div class="ms-item">
            <div class="ms-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none"><rect x="3" y="3" width="18" height="14" rx="2" stroke="#fff" stroke-width="1.5"/><path d="M7 7h10M7 11h10" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round"/></svg>
            </div>
            <h3 class="ms-item-title">Paid Advertisements</h3>
            <p class="ms-item-desc">Maximize your visibility and target the right audience through strategic paid advertising campaigns.</p>
          </div>
          <div class="ms-item">
            <div class="ms-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none"><circle cx="12" cy="12" r="9" stroke="#8E60EE" stroke-width="1.5"/><path d="M12 7v5l3 3" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </div>
            <h3 class="ms-item-title">Public Relations</h3>
            <p class="ms-item-desc">Shape and manage your brand's reputation through effective public relations strategies.</p>
          </div>
          <div class="ms-item">
            <div class="ms-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none"><path d="M3 5h18v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5Z" stroke="#fff" stroke-width="1.5"/><path d="M3 5l9 6 9-6" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </div>
            <h3 class="ms-item-title">Press releases</h3>
            <p class="ms-item-desc">Amplify your brand's message and reach with impactful press releases for more networking.</p>
          </div>
          <div class="ms-item">
            <div class="ms-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none"><path d="M13 2l1 4h4l-3 2 1 4-4-2-4 2 1-4-3-2h4l1-4Z" stroke="#8E60EE" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 8v10" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round"/></svg>
            </div>
            <h3 class="ms-item-title">Social Media</h3>
            <p class="ms-item-desc">Optimize your social media presence and engage with your audience effectively.</p>
          </div>
          <div class="ms-item">
            <div class="ms-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none"><path d="M3 4h18v14H3V4Z" stroke="#fff" stroke-width="1.5"/><path d="M8 18h8M5 18h14" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round"/></svg>
            </div>
            <h3 class="ms-item-title">Content Creation</h3>
            <p class="ms-item-desc">Create compelling and engaging content that resonates with your target audience.</p>
          </div>
          <div class="ms-item">
            <div class="ms-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none"><rect x="2" y="4" width="20" height="12" rx="2" stroke="#8E60EE" stroke-width="1.5"/><path d="M6 18h12M4 20h16" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round"/></svg>
            </div>
            <h3 class="ms-item-title">Billboards</h3>
            <p class="ms-item-desc">Make a bold statement and capture attention with eye-catching billboard advertising.</p>
          </div>
          <div class="ms-item">
            <div class="ms-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none"><circle cx="12" cy="12" r="9" stroke="#fff" stroke-width="1.5"/><path d="M12 6v6m-3-3h6" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round"/></svg>
            </div>
            <h3 class="ms-item-title">Community</h3>
            <p class="ms-item-desc">Foster meaningful connections and engagement within your community.</p>
          </div>
        </div>
      </div>
    </section>

    <!-- FAQ -->
    <FAQ :items="marketingFaqs"
         title="Marketing FAQ"
         description="Answers to common questions about our marketing services, strategies, and how we can help your project." />

    <!-- CTA -->
    <section id="marketing-contact" class="marketing-cta-section">
      <div class="mc-wrap">
        <h2 class="mc-title">Need marketing for your project?</h2>
        <p class="mc-intro">Request now to get in contact with the Solidproof team!</p>
        <a href="https://solidproof.io/contact" class="mc-button">
          <span>Request now</span>
          <svg class="mc-arrow" width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <path d="M3 8h8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
            <path d="M8 3l5 5-5 5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </a>
      </div>
    </section>
  </main>
</template>

<script setup>
import FAQ from '../components/FAQ.vue'

const marketingFaqs = [
  { question: 'What marketing services does Solidproof.io provide for the blockchain industry?', answer: 'Solidproof.io offers a range of marketing services tailored for the blockchain industry, including strategic planning, branding, digital marketing, content creation, social media management, and community engagement.' },
  { question: 'Why is marketing important for blockchain projects and businesses?', answer: 'Marketing is crucial for blockchain projects and businesses to increase awareness, build trust, attract users or investors, and differentiate themselves in a competitive market. Effective marketing strategies help showcase the value and potential of blockchain solutions.' },
  { question: 'How does Solidproof.io help blockchain projects with strategic planning?', answer: 'Solidproof.io provides strategic planning services to help blockchain projects define their goals, target audience, messaging, and competitive positioning. We work closely with clients to develop tailored marketing strategies that align with their business objectives.' },
  { question: 'Can Solidproof.io assist with branding for blockchain projects?', answer: 'Yes, Solidproof.io offers branding services specifically designed for blockchain projects. We help create unique brand identities, including logo design, brand messaging, and visual assets, to effectively communicate the project\'s vision and values.' },
  { question: 'What digital marketing channels does Solidproof.io utilize for blockchain projects?', answer: 'Solidproof.io leverages various digital marketing channels, including search engine optimization (SEO), social media advertising, email marketing, influencer marketing, and content marketing, to reach the target audience and drive engagement.' },
  { question: 'Does Solidproof.io create content for blockchain projects?', answer: 'Yes, Solidproof.io provides content creation services for blockchain projects. This includes blog posts, whitepapers, case studies, infographics, video scripts, and other engaging content formats to educate and engage the target audience.' },
]
</script>

<style scoped>
.marketing-page { flex: 1; display: flex; flex-direction: column; background: transparent; }

/* Hero */
.marketing-hero { padding: 160px 20px 64px; position: relative; }
.marketing-hero-inner { max-width: 1240px; margin: 0 auto; display: grid; grid-template-columns: 1.1fr 0.9fr; gap: 32px; align-items: center; }
.marketing-hero-copy { display: flex; flex-direction: column; gap: 16px; }
.marketing-hero-title { color: #fff; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 56px; font-weight: 700; line-height: 1.08; margin: 0; }
.marketing-hero-subtitle { color: #9BA1A5; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 18px; line-height: 1.6; margin: 0; }
.marketing-hero-ctas { display: flex; gap: 12px; margin-top: 4px; }
.marketing-cta { display: inline-block; padding: 12px 18px; border-radius: 8px; text-decoration: none; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 14px; font-weight: 500; line-height: 1; transition: all 0.25s ease; }
.marketing-cta--primary { background: #0D6EFD; color: #fff; }
.marketing-cta--primary:hover { background: #0B5ED7; transform: translateY(-1px); }
.marketing-cta--ghost { background: transparent; color: #fff; border: 1px solid rgba(255,255,255,0.18); }
.marketing-cta--ghost:hover { border-color: rgba(255,255,255,0.32); transform: translateY(-1px); }
.marketing-hero-art { position: relative; min-height: 320px; }
.marketing-hero-svg { position: absolute; inset: 0; width: 100%; height: 100%; opacity: 0.7; }
.marketing-orb { position: absolute; border-radius: 50%; filter: blur(40px); opacity: 0.6; }
.marketing-orb--lg { width: 240px; height: 240px; right: 10%; bottom: 0; background: radial-gradient(60% 60% at 50% 50%, rgba(142,96,238,0.9), rgba(13,110,253,0.3)); }
.marketing-orb--sm { width: 160px; height: 160px; left: 5%; top: 20%; background: radial-gradient(60% 60% at 50% 50%, rgba(106,255,179,0.8), rgba(13,110,253,0.3)); }

/* Intro */
.marketing-intro { padding: 24px 20px 8px; }
.mi-wrap { max-width: 1240px; margin: 0 auto; }
.mi-text { color: #9BA1A5; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 16px; line-height: 1.6; margin: 0 auto; max-width: 1000px; text-align: center; }

/* Services */
.marketing-services { padding: 32px 20px; }
.ms-wrap { max-width: 1240px; margin: 0 auto; }
.ms-title { color: #fff; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 36px; font-weight: 700; line-height: 1.2; margin: 0 0 16px; text-align: center; }
.ms-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
.ms-item { display: flex; flex-direction: column; align-items: center; text-align: center; gap: 12px; padding: 24px 16px; border-radius: 16px; background: #0F1011; border: 1px solid rgba(255,255,255,0.08); transition: all 0.25s ease; }
.ms-item:hover { background: rgba(15, 16, 17, 0.8); border-color: rgba(255,255,255,0.12); }
.ms-icon { display: flex; align-items: center; justify-content: center; width: 40px; height: 40px; border-radius: 12px; background: linear-gradient(180deg, rgba(47, 47, 51, 0.87) 0%, rgba(61, 62, 67, 0.87) 34.82%, rgba(47, 47, 51, 0.87) 100%), #2F2F33; border: 1px solid #606061; flex-shrink: 0; }
.ms-icon svg { width: 22px; height: 22px; }
.ms-item-title { color: #fff; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 15px; font-weight: 600; line-height: 1.2; margin: 0; }
.ms-item-desc { color: #9BA1A5; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 13px; line-height: 1.4; margin: 0; }

/* CTA */
.marketing-cta-section { position: relative; padding: 72px 20px 72px; overflow: hidden; }
.marketing-cta-section::before { content: ""; position: absolute; inset: 0; background:
  radial-gradient(60% 120% at 50% 100%, rgba(13,110,253,0.14), rgba(0,0,0,0) 60%),
  linear-gradient(180deg, rgba(0,0,0,0.55), rgba(0,0,0,0.55)); z-index: 0; pointer-events: none; }
.marketing-cta-section::after { content: ""; position: absolute; inset: 0; background:
  radial-gradient(80% 100% at 50% 50%, rgba(0,0,0,0) 60%, rgba(0,0,0,0.5) 100%); z-index: 0; pointer-events: none; }
.mc-wrap { max-width: 1240px; margin: 0 auto; display: flex; flex-direction: column; gap: 14px; align-items: center; text-align: center; padding: 0; background: transparent; border: 0; position: relative; z-index: 1; }
.mc-title { color: #fff; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 36px; font-weight: 700; line-height: 1.25; margin: 0; }
.mc-intro { color: #D1D5DB; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 14px; line-height: 1.6; margin: 0; max-width: 760px; }
.mc-button { display: inline-flex; align-items: center; gap: 8px; margin-top: 10px; padding: 12px 22px; border-radius: 9999px; background: linear-gradient(180deg, #2B2C2F 0%, #1E1F22 100%), #202124; color: #fff; text-decoration: none; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 14px; font-weight: 600; line-height: 1; transition: all 0.25s ease; border: 1px solid rgba(255,255,255,0.12); box-shadow: 0 8px 24px rgba(0,0,0,0.45), inset 0 1px rgba(255,255,255,0.06); }
.mc-button:hover { background: linear-gradient(180deg, #323338 0%, #222427 100%); transform: translateY(-1px); box-shadow: 0 10px 28px rgba(0,0,0,0.55), inset 0 1px rgba(255,255,255,0.08); }
.mc-arrow { display: inline-block; }

/* Responsive */
@media (max-width: 1180px) {
  .marketing-hero-inner { grid-template-columns: 1fr; }
  .ms-grid { grid-template-columns: repeat(2, 1fr); }
}
@media (max-width: 768px) {
  .marketing-hero { padding: 140px 16px 48px; }
  .marketing-hero-title { font-size: 40px; }
  .marketing-hero-subtitle { font-size: 16px; }
  .marketing-hero-ctas { flex-wrap: wrap; }
  .ms-grid { grid-template-columns: 1fr; }
  .mc-title { font-size: 24px; }
}

@media (prefers-reduced-motion: reduce) {
  .marketing-cta, .mc-button { transition: none; }
}
</style>

// src/routes/marketing/+page.svelte
<svelte:head>
	<title>Marketing • SolidProof</title>
</svelte:head>

<script>
	import FAQ from '$lib/components/FAQ.svelte'

	const marketingFaqs = [
		{ question: 'What marketing services does Solidproof.io provide for the blockchain industry?', answer: 'Solidproof.io offers a range of marketing services tailored for the blockchain industry, including strategic planning, branding, digital marketing, content creation, social media management, and community engagement.' },
		{ question: 'Why is marketing important for blockchain projects and businesses?', answer: 'Marketing is crucial for blockchain projects and businesses to increase awareness, build trust, attract users or investors, and differentiate themselves in a competitive market. Effective marketing strategies help showcase the value and potential of blockchain solutions.' },
		{ question: 'How does Solidproof.io help blockchain projects with strategic planning?', answer: 'Solidproof.io provides strategic planning services to help blockchain projects define their goals, target audience, messaging, and competitive positioning. We work closely with clients to develop tailored marketing strategies that align with their business objectives.' },
		{ question: 'Can Solidproof.io assist with branding for blockchain projects?', answer: 'Yes, Solidproof.io offers branding services specifically designed for blockchain projects. We help create unique brand identities, including logo design, brand messaging, and visual assets, to effectively communicate the project\'s vision and values.' },
		{ question: 'What digital marketing channels does Solidproof.io utilize for blockchain projects?', answer: 'Solidproof.io leverages various digital marketing channels, including search engine optimization (SEO), social media advertising, email marketing, influencer marketing, and content marketing, to reach the target audience and drive engagement.' },
		{ question: 'Does Solidproof.io create content for blockchain projects?', answer: 'Yes, Solidproof.io provides content creation services for blockchain projects. This includes blog posts, whitepapers, case studies, infographics, video scripts, and other engaging content formats to educate and engage the target audience.' },
	]
</script>

<main class="marketing-page" aria-labelledby="marketing-hero-title">
	<!-- Hero -->
	<section class="marketing-hero">
		<div class="marketing-hero-inner">
			<div class="marketing-hero-copy">
				<h1 id="marketing-hero-title" class="marketing-hero-title">Marketing</h1>
				<p class="marketing-hero-subtitle">
					Unlock the Power of Secure Marketing with SolidProof. Our comprehensive range of meticulously vetted marketing solutions, in collaboration with top-tier agencies, empowers businesses to achieve their goals.
				</p>
				<div class="marketing-hero-ctas">
					<a href="https://t.me/solidproof_io" target="_blank" class="marketing-cta marketing-cta--primary">Request Marketing</a>
					<a href="#marketing-services" class="marketing-cta marketing-cta--ghost">Learn more</a>
				</div>
			</div>
			<div class="marketing-hero-art" aria-hidden="true">
				<div class="marketing-orb marketing-orb--lg"></div>
				<div class="marketing-orb marketing-orb--sm"></div>
				<svg class="marketing-hero-svg" viewBox="0 0 160 160" fill="none" aria-hidden="true">
					<defs>
						<linearGradient id="gm1" x1="0" y1="0" x2="1" y2="1">
							<stop offset="0" stop-color="#6AFFB3" />
							<stop offset="1" stop-color="#8E60EE" />
						</linearGradient>
					</defs>
					<circle cx="80" cy="80" r="72" stroke="url(#gm1)" stroke-width="2" opacity="0.6" />
					<circle cx="80" cy="80" r="52" stroke="url(#gm1)" stroke-width="2" opacity="0.35" />
					<circle cx="80" cy="80" r="28" stroke="url(#gm1)" stroke-width="2" opacity="0.25" />
				</svg>
			</div>
		</div>
	</section>

	<!-- Intro -->
	<section class="marketing-intro">
		<div class="mi-wrap">
			<p class="mi-text">
				SolidProof offers clients a wide range of marketing solutions that have successfully passed our security checks. We are partnered with multiple high-class marketing agencies and work together with our clients to find the best solutions that suit their goals. Our marketing arsenal leaves no stone unturned, giving clients a one-stop place for all of their marketing needs. Going with SolidProof allows you to find the highest quality solutions at the best prices possible. We can assist with the following:
			</p>
		</div>
	</section>

	<!-- Services -->
	<section id="marketing-services" class="marketing-services" aria-labelledby="marketing-services-title">
		<div class="ms-wrap">
			<h2 id="marketing-services-title" class="ms-title">Marketing Services</h2>
			<div class="ms-grid">
				<div class="ms-item">
					<div class="ms-icon" aria-hidden="true">
						<svg viewBox="0 0 24 24" width="24" height="24" fill="none"><path d="M3 3v18h18" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" /><path d="M7 16v-5M12 16v-8M17 16v-3" stroke="#8E60EE" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" /></svg>
					</div>
					<h3 class="ms-item-title">Influencer Marketing</h3>
					<p class="ms-item-desc">Harness the power of influential individuals to promote your brand and drive engagement</p>
				</div>
				<div class="ms-item">
					<div class="ms-icon" aria-hidden="true">
						<svg viewBox="0 0 24 24" width="24" height="24" fill="none"><rect x="3" y="3" width="18" height="14" rx="2" stroke="#fff" stroke-width="1.5" /><path d="M7 7h10M7 11h10" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" /></svg>
					</div>
					<h3 class="ms-item-title">Paid Advertisements</h3>
					<p class="ms-item-desc">Maximize your visibility and target the right audience through strategic paid advertising campaigns.</p>
				</div>
				<div class="ms-item">
					<div class="ms-icon" aria-hidden="true">
						<svg viewBox="0 0 24 24" width="24" height="24" fill="none"><circle cx="12" cy="12" r="9" stroke="#8E60EE" stroke-width="1.5" /><path d="M12 7v5l3 3" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" /></svg>
					</div>
					<h3 class="ms-item-title">Public Relations</h3>
					<p class="ms-item-desc">Shape and manage your brand's reputation through effective public relations strategies.</p>
				</div>
				<div class="ms-item">
					<div class="ms-icon" aria-hidden="true">
						<svg viewBox="0 0 24 24" width="24" height="24" fill="none"><path d="M3 5h18v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5Z" stroke="#fff" stroke-width="1.5" /><path d="M3 5l9 6 9-6" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" /></svg>
					</div>
					<h3 class="ms-item-title">Press releases</h3>
					<p class="ms-item-desc">Amplify your brand's message and reach with impactful press releases for more networking.</p>
				</div>
				<div class="ms-item">
					<div class="ms-icon" aria-hidden="true">
						<svg viewBox="0 0 24 24" width="24" height="24" fill="none"><path d="M13 2l1 4h4l-3 2 1 4-4-2-4 2 1-4-3-2h4l1-4Z" stroke="#8E60EE" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" /><path d="M12 8v10" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" /></svg>
					</div>
					<h3 class="ms-item-title">Social Media</h3>
					<p class="ms-item-desc">Optimize your social media presence and engage with your audience effectively.</p>
				</div>
				<div class="ms-item">
					<div class="ms-icon" aria-hidden="true">
						<svg viewBox="0 0 24 24" width="24" height="24" fill="none"><path d="M3 4h18v14H3V4Z" stroke="#fff" stroke-width="1.5" /><path d="M8 18h8M5 18h14" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" /></svg>
					</div>
					<h3 class="ms-item-title">Content Creation</h3>
					<p class="ms-item-desc">Create compelling and engaging content that resonates with your target audience.</p>
				</div>
				<div class="ms-item">
					<div class="ms-icon" aria-hidden="true">
						<svg viewBox="0 0 24 24" width="24" height="24" fill="none"><rect x="2" y="4" width="20" height="12" rx="2" stroke="#8E60EE" stroke-width="1.5" /><path d="M6 18h12M4 20h16" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" /></svg>
					</div>
					<h3 class="ms-item-title">Billboards</h3>
					<p class="ms-item-desc">Make a bold statement and capture attention with eye-catching billboard advertising.</p>
				</div>
				<div class="ms-item">
					<div class="ms-icon" aria-hidden="true">
						<svg viewBox="0 0 24 24" width="24" height="24" fill="none"><circle cx="12" cy="12" r="9" stroke="#fff" stroke-width="1.5" /><path d="M12 6v6m-3-3h6" stroke="#6AFFB3" stroke-width="1.5" stroke-linecap="round" /></svg>
					</div>
					<h3 class="ms-item-title">Community</h3>
					<p class="ms-item-desc">Foster meaningful connections and engagement within your community.</p>
				</div>
			</div>
		</div>
	</section>

	<!-- FAQ -->
	<FAQ
		items={marketingFaqs}
		title="Marketing FAQ"
		description="Answers to common questions about our marketing services, strategies, and how we can help your project."
	/>

	<!-- CTA -->
	<section id="marketing-contact" class="marketing-cta-section">
		<div class="mc-wrap">
			<h2 class="mc-title">Need marketing for your project?</h2>
			<p class="mc-intro">Request now to get in contact with the Solidproof team!</p>
			<a href="https://solidproof.io/contact" class="mc-button">
				<span>Request now</span>
				<svg class="mc-arrow" width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
					<path d="M3 8h8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
					<path d="M8 3l5 5-5 5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
				</svg>
			</a>
		</div>
	</section>
</main>

<style>
.marketing-page { flex: 1; display: flex; flex-direction: column; background: transparent; }

/* Hero */
.marketing-hero { padding: 160px 20px 64px; position: relative; }
.marketing-hero-inner { max-width: 1240px; margin: 0 auto; display: grid; grid-template-columns: 1.1fr 0.9fr; gap: 32px; align-items: center; }
.marketing-hero-copy { display: flex; flex-direction: column; gap: 16px; }
.marketing-hero-title { color: #fff; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 56px; font-weight: 700; line-height: 1.08; margin: 0; }
.marketing-hero-subtitle { color: #9BA1A5; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 18px; line-height: 1.6; margin: 0; }
.marketing-hero-ctas { display: flex; gap: 12px; margin-top: 4px; }
.marketing-cta { display: inline-block; padding: 12px 18px; border-radius: 8px; text-decoration: none; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 14px; font-weight: 500; line-height: 1; transition: all 0.25s ease; }
.marketing-cta--primary { background: #0D6EFD; color: #fff; }
.marketing-cta--primary:hover { background: #0B5ED7; transform: translateY(-1px); }
.marketing-cta--ghost { background: transparent; color: #fff; border: 1px solid rgba(255,255,255,0.18); }
.marketing-cta--ghost:hover { border-color: rgba(255,255,255,0.32); transform: translateY(-1px); }
.marketing-hero-art { position: relative; min-height: 320px; }
.marketing-hero-svg { position: absolute; inset: 0; width: 100%; height: 100%; opacity: 0.7; }
.marketing-orb { position: absolute; border-radius: 50%; filter: blur(40px); opacity: 0.6; }
.marketing-orb--lg { width: 240px; height: 240px; right: 10%; bottom: 0; background: radial-gradient(60% 60% at 50% 50%, rgba(142,96,238,0.9), rgba(13,110,253,0.3)); }
.marketing-orb--sm { width: 160px; height: 160px; left: 5%; top: 20%; background: radial-gradient(60% 60% at 50% 50%, rgba(106,255,179,0.8), rgba(13,110,253,0.3)); }

/* Intro */
.marketing-intro { padding: 24px 20px 8px; }
.mi-wrap { max-width: 1240px; margin: 0 auto; }
.mi-text { color: #9BA1A5; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 16px; line-height: 1.6; margin: 0 auto; max-width: 1000px; text-align: center; }

/* Services */
.marketing-services { padding: 32px 20px; }
.ms-wrap { max-width: 1240px; margin: 0 auto; }
.ms-title { color: #fff; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 36px; font-weight: 700; line-height: 1.2; margin: 0 0 16px; text-align: center; }
.ms-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
.ms-item { display: flex; flex-direction: column; align-items: center; text-align: center; gap: 12px; padding: 24px 16px; border-radius: 16px; background: #0F1011; border: 1px solid rgba(255,255,255,0.08); transition: all 0.25s ease; }
.ms-item:hover { background: rgba(15, 16, 17, 0.8); border-color: rgba(255,255,255,0.12); }
.ms-icon { display: flex; align-items: center; justify-content: center; width: 40px; height: 40px; border-radius: 12px; background: linear-gradient(180deg, rgba(47, 47, 51, 0.87) 0%, rgba(61, 62, 67, 0.87) 34.82%, rgba(47, 47, 51, 0.87) 100%), #2F2F33; border: 1px solid #606061; flex-shrink: 0; }
.ms-icon svg { width: 22px; height: 22px; }
.ms-item-title { color: #fff; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 15px; font-weight: 600; line-height: 1.2; margin: 0; }
.ms-item-desc { color: #9BA1A5; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 13px; line-height: 1.4; margin: 0; }

/* CTA */
.marketing-cta-section { position: relative; padding: 72px 20px 72px; overflow: hidden; }
.marketing-cta-section::before { content: ""; position: absolute; inset: 0; background:
  radial-gradient(60% 120% at 50% 100%, rgba(13,110,253,0.14), rgba(0,0,0,0) 60%),
  linear-gradient(180deg, rgba(0,0,0,0.55), rgba(0,0,0,0.55)); z-index: 0; pointer-events: none; }
.marketing-cta-section::after { content: ""; position: absolute; inset: 0; background:
  radial-gradient(80% 100% at 50% 50%, rgba(0,0,0,0) 60%, rgba(0,0,0,0.5) 100%); z-index: 0; pointer-events: none; }
.mc-wrap { max-width: 1240px; margin: 0 auto; display: flex; flex-direction: column; gap: 14px; align-items: center; text-align: center; padding: 0; background: transparent; border: 0; position: relative; z-index: 1; }
.mc-title { color: #fff; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 36px; font-weight: 700; line-height: 1.25; margin: 0; }
.mc-intro { color: #D1D5DB; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 14px; line-height: 1.6; margin: 0; max-width: 760px; }
.mc-button { display: inline-flex; align-items: center; gap: 8px; margin-top: 10px; padding: 12px 22px; border-radius: 9999px; background: linear-gradient(180deg, #2B2C2F 0%, #1E1F22 100%), #202124; color: #fff; text-decoration: none; font-family: 'Geist', -apple-system, Roboto, Helvetica, sans-serif; font-size: 14px; font-weight: 600; line-height: 1; transition: all 0.25s ease; border: 1px solid rgba(255,255,255,0.12); box-shadow: 0 8px 24px rgba(0,0,0,0.45), inset 0 1px rgba(255,255,255,0.06); }
.mc-button:hover { background: linear-gradient(180deg, #323338 0%, #222427 100%); transform: translateY(-1px); box-shadow: 0 10px 28px rgba(0,0,0,0.55), inset 0 1px rgba(255,255,255,0.08); }
.mc-arrow { display: inline-block; }

/* Responsive */
@media (max-width: 1180px) {
  .marketing-hero-inner { grid-template-columns: 1fr; }
  .ms-grid { grid-template-columns: repeat(2, 1fr); }
}
@media (max-width: 768px) {
  .marketing-hero { padding: 140px 16px 48px; }
  .marketing-hero-title { font-size: 40px; }
  .marketing-hero-subtitle { font-size: 16px; }
  .marketing-hero-ctas { flex-wrap: wrap; }
  .ms-grid { grid-template-columns: 1fr; }
  .mc-title { font-size: 24px; }
}

@media (prefers-reduced-motion: reduce) {
  .marketing-cta, .mc-button { transition: none; }
}
</style>
